# This rule is not used by the project sync-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over iot.s4t.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: device-admin-role
rules:
- apiGroups:
  - iot.s4t.io
  resources:
  - devices
  verbs:
  - '*'
- apiGroups:
  - iot.s4t.io
  resources:
  - devices/status
  verbs:
  - get
