apiVersion: iot.s4t.io/v1alpha1
kind: Device
metadata:
  labels:
    app.kubernetes.io/name: sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: device-sample
spec:
  # TODO(user): Add fields here
