
services:

  # ... (i tuoi servizi keycloak, postgres, keystone, mariadb rimangono uguali) ...
  # Assicurati solo che keystone sia accessibile a horizon tramite la rete auth-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password_keycloak

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_PROXY: edge
    ports:
      - "8081:8080"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./keycloak-config/stack4things-realm.json:/opt/keycloak/data/import/stack4things-realm.json
    networks:
      - auth-net
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-net

  keystone:
    build: .
    container_name: keystone
    command: ["/usr/local/bin/keystone-entrypoint.sh"]
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mariadb
      DB_PASSWORD: password_keystone
    volumes:
      - ./keystone-config/keystone.conf:/etc/keystone/keystone.conf
      - ./keystone-config/keystone-mapping.json:/etc/keystone/keystone-mapping.json
      - ./keystone-config/sso_callback.html:/etc/keystone/sso_callback.html
      - ./keystone-config/wsgi-keystone.conf:/etc/apache2/sites-enabled/keystone.conf
    networks:
      - auth-net
    depends_on:
      - mariadb
      - keycloak

  

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: keystone
      MARIADB_USER: keystone
      MARIADB_PASSWORD: password_keystone
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - auth-net
      
volumes:
  postgres_data:
  mariadb_data:

networks:
  auth-net:
    driver: bridge
